//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OTMST.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOTMST_Artisans
    {
        public int ArtisanID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Art { get; set; }
        public int TourStop { get; set; }
        public string PageImage { get; set; }
        public string CatalogImage { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public string PageStatement { get; set; }
        public string BusinessName { get; set; }
        public string ArtisanStatus { get; set; }
        public IEnumerable<string> Images { get; set; }
    }
}
